export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const MAP_ZOOMIN = 'MAP_ZOOMIN'
export const MAP_ZOOMOUT = 'MAP_ZOOMOUT'

export const TOGGLE_MARKERS = 'TOGGLE_MARKERS'

export const SET_CENTER = 'SET_CENTER'

export const CURRENT_MARKERS = 'CURRENT_MARKERS'

export const LOADED_STATUS = 'LOADED_STATUS'